server:
  port: 8080
debug: false
spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
    webflux:
      # 欢迎页不能使用
      static-path-pattern: /resources/**
    content negotiation:
      favor-parameter: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
mybatis-plus:
  type-aliases-package: org.qingqiao